#include "platform.h"

#if defined(USE_GC)

#include "ThirdParty/gc/allchblk.c"
#include "ThirdParty/gc/alloc.c"
#include "ThirdParty/gc/backgraph.c"
#include "ThirdParty/gc/blacklst.c"
#include "ThirdParty/gc/checksums.c"
#include "ThirdParty/gc/dyn_load.c"
#include "ThirdParty/gc/finalize.c"
#include "ThirdParty/gc/headers.c"
#include "ThirdParty/gc/mach_dep.c"
#include "ThirdParty/gc/malloc.c"
#include "ThirdParty/gc/mallocx.c"
#include "ThirdParty/gc/mark.c"
#include "ThirdParty/gc/mark_rts.c"
#include "ThirdParty/gc/misc.c"
#include "ThirdParty/gc/new_hblk.c"
#include "ThirdParty/gc/obj_map.c"
#include "ThirdParty/gc/os_dep.c"
#include "ThirdParty/gc/pcr_interface.c"
#include "ThirdParty/gc/ptr_chck.c"
#include "ThirdParty/gc/real_malloc.c"
#include "ThirdParty/gc/reclaim.c"
#include "ThirdParty/gc/specific.c"
#include "ThirdParty/gc/stubborn.c"
#include "ThirdParty/gc/thread_local_alloc.c"
#include "ThirdParty/gc/typd_mlc.c"
#include "ThirdParty/gc/win32_threads.c"

#endif