#if !defined( YOLK_SCENE_GENERIC_TEXTURE_FORMAT_H_ ) || defined( GTF_START_MACRO )

#if !defined GTF_START_MACRO
	#define YOLK_SCENE_GENERIC_TEXTURE_FORMAT_H_ 1
	#define GTF_START_MACRO enum GENERIC_TEXTURE_FORMAT {
#else
	#if !defined( GTF_MOD_MACRO )
		#error GTF_START_MACRO set but not GTF_MOD_MACRO
	#elif !defined( GTF_END_MACRO )
		#error GTF_START_MACRO set but not GTF_END_MACRO
	#endif
#endif

#if !defined GTF_MOD_MACRO
#define GTF_MOD_MACRO(x) GTF_##x,
#endif

#if !defined GTF_END_MACRO
#define GTF_END_MACRO };
#endif

GTF_START_MACRO
	GTF_MOD_MACRO( RGBA2 )
	GTF_MOD_MACRO( RGBA4 )
	GTF_MOD_MACRO( RGB5_A1 )
	GTF_MOD_MACRO( RGBA8 )
	GTF_MOD_MACRO( RGBA8I )
	GTF_MOD_MACRO( RGBA8UI )
	GTF_MOD_MACRO( RGBA8_SNORM )
	GTF_MOD_MACRO( SRGB8_ALPHA8 )
	GTF_MOD_MACRO( RGB10_A2 )
	GTF_MOD_MACRO( RGB10_A2UI )
	GTF_MOD_MACRO( RGBA12 )
	GTF_MOD_MACRO( RGBA16 )
	GTF_MOD_MACRO( RGBA16F )
	GTF_MOD_MACRO( RGBA16I )
	GTF_MOD_MACRO( RGBA16UI )
	GTF_MOD_MACRO( RGBA16_SNORM )
	GTF_MOD_MACRO( RGBA32F )
	GTF_MOD_MACRO( RGBA32I )
	GTF_MOD_MACRO( RGBA32UI )
	GTF_MOD_MACRO( COMPRESSED_RGBA_S3TC_DXT1 )
	GTF_MOD_MACRO( COMPRESSED_RGBA_S3TC_DXT3 )
	GTF_MOD_MACRO( COMPRESSED_RGBA_S3TC_DXT5 )
	GTF_MOD_MACRO( COMPRESSED_SRGB_ALPHA_S3TC_DXT1 )
	GTF_MOD_MACRO( COMPRESSED_SRGB_ALPHA_S3TC_DXT3 )
	GTF_MOD_MACRO( COMPRESSED_SRGB_ALPHA_S3TC_DXT5 )
	GTF_MOD_MACRO( COMPRESSED_RGBA_BPTC_UNORM )
	GTF_MOD_MACRO( COMPRESSED_SRGB_ALPHA_BPTC_UNORM )
	GTF_MOD_MACRO( COMPRESSED_RGBA )
	GTF_MOD_MACRO( COMPRESSED_SRGB_ALPHA )
	GTF_MOD_MACRO( R3_G3_B2 )
	GTF_MOD_MACRO( RGB4 )
	GTF_MOD_MACRO( RGB5 )
	GTF_MOD_MACRO( RGB8 )
	GTF_MOD_MACRO( RGB8I )
	GTF_MOD_MACRO( RGB8UI )
	GTF_MOD_MACRO( RGB8_SNORM )
	GTF_MOD_MACRO( SRGB8 )
	GTF_MOD_MACRO( RGB9_E5 )
	GTF_MOD_MACRO( R11F_G11F_B10F )
	GTF_MOD_MACRO( RGB16 )
	GTF_MOD_MACRO( RGB16F )
	GTF_MOD_MACRO( RGB16I )
	GTF_MOD_MACRO( RGB16UI )
	GTF_MOD_MACRO( RGB16_SNORM )
	GTF_MOD_MACRO( RGB32F )
	GTF_MOD_MACRO( RGB32I )
	GTF_MOD_MACRO( RGB32UI )
	GTF_MOD_MACRO( COMPRESSED_RGB_S3TC_DXT1 )
	GTF_MOD_MACRO( COMPRESSED_SRGB_S3TC_DXT1 )
	GTF_MOD_MACRO( COMPRESSED_RGB_BPTC_SIGNED_FLOAT )
	GTF_MOD_MACRO( COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT )
	GTF_MOD_MACRO( COMPRESSED_RGB )
	GTF_MOD_MACRO( COMPRESSED_SRGB )
	GTF_MOD_MACRO( RG8 )
	GTF_MOD_MACRO( RG8I )
	GTF_MOD_MACRO( RG8UI )
	GTF_MOD_MACRO( RG8_SNORM )
	GTF_MOD_MACRO( RG16 )
	GTF_MOD_MACRO( RG16F )
	GTF_MOD_MACRO( RG16I )
	GTF_MOD_MACRO( RG16UI )
	GTF_MOD_MACRO( RG16_SNORM )
	GTF_MOD_MACRO( RG32F )
	GTF_MOD_MACRO( RG32I )
	GTF_MOD_MACRO( RG32UI )
	GTF_MOD_MACRO( COMPRESSED_RG_RGTC2 )
	GTF_MOD_MACRO( COMPRESSED_SIGNED_RG_RGTC2 )
	GTF_MOD_MACRO( COMPRESSED_RG )
	GTF_MOD_MACRO( DEPTH24_STENCIL8 )
	GTF_MOD_MACRO( DEPTH32F_STENCIL8 )
	GTF_MOD_MACRO( R8 )
	GTF_MOD_MACRO( R8I )
	GTF_MOD_MACRO( R8UI )
	GTF_MOD_MACRO( R8_SNORM )
	GTF_MOD_MACRO( R16 )
	GTF_MOD_MACRO( R16F )
	GTF_MOD_MACRO( R16I )
	GTF_MOD_MACRO( R16UI )
	GTF_MOD_MACRO( R16_SNORM )
	GTF_MOD_MACRO( R32F )
	GTF_MOD_MACRO( R32I )
	GTF_MOD_MACRO( R32UI )
	GTF_MOD_MACRO( COMPRESSED_RED_RGTC1 )
	GTF_MOD_MACRO( COMPRESSED_SIGNED_RED_RGTC1 )
	GTF_MOD_MACRO( COMPRESSED_RED )
	GTF_MOD_MACRO( DEPTH_COMPONENT16 )
	GTF_MOD_MACRO( DEPTH_COMPONENT24 )
	GTF_MOD_MACRO( DEPTH_COMPONENT32 )
	GTF_MOD_MACRO( DEPTH_COMPONENT32F )
GTF_END_MACRO

#undef GTF_START_MACRO
#undef GTF_MOD_MACRO
#undef GTF_END_MACRO
	
#endif